project:
  type: website
  render:
    - index.qmd
    - 404.qmd
  resources:
    - "files/"
  preview:
    port: 3333

execute:
  engine: markdown

bibliography: files/bib/readings.bib
csl: files/bib/chicago-author-date.csl

website:
  title: "Nexellence"
  description: "Nexellence course materials"
  site-url: "https://nexellence.hussainhadah.com/"

  draft-mode: unlinked

  announcement:
    icon: calendar-check
    dismissable: true
    content: "**Welcome!** Check the schedule for important dates and deadlines"
    type: info
    position: below-navbar

  favicon: "/files/favicon-512.png"

  open-graph:
    image: "/files/social-image-f25.png"
    locale: en_US

  repo-url: "https://github.com/hhadah/nexellence-summer-material"
  repo-actions: [source, issue]

  page-navigation: true

  navbar:
    pinned: true
    background: "#4E2A84"

  page-footer:
    left: |
      Content {{< fa brands creative-commons >}} {{< var course.copyright_year >}} by [{{< var instructor.name_no_title >}}]({{< var instructor.url >}}) <br>
      All content licensed under a {{< fa brands creative-commons >}}
      {{< fa brands creative-commons-by >}} {{< fa brands creative-commons-nc >}}
      [Creative Commons Attribution-NonCommercial 4.0 International license (CC BY-NC 4.0)](https://creativecommons.org/licenses/by-nc/4.0/)
    right: |
      Made with {{< fa brands r-project >}} and [Quarto](https://quarto.org/)<br>
      [View the source at {{< fa brands github >}} GitHub]({{< var course.github >}})

format:
  html:
    theme:
      - litera
      - html/custom.scss
    toc: true
    highlight-style: monokai

language: 
  draft: "This is a draft—the full FAQ post isn't finished yet."
